language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

mysql:
  database: travis_ci_drupal_module_example_test
  username: root
  encoding: utf8

before_install:

 # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database travis_ci_drupal_module_example_test'
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/travis_ci_drupal_module_example_test --enable=simpletest travis_ci_drupal_module_example_test

  # reference and enable travis_ci_drupal_module_example in build site
  - ln -s $(readlink -e $(cd -)) travis_ci_drupal_module_example_test/drupal/sites/all/modules/travis_ci_drupal_module_example
  - cd travis_ci_drupal_module_example_test/drupal
  - drush --yes pm-enable travis_ci_drupal_module_example

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run 'Travis-CI Drupal Module Example' --uri=http://127.0.0.1:8080
