language: php

php:
  - 7.0
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist

script:
  - ./bin/ci/install_dependencies.sh
  - php vendor/vendors.php
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql
   - composer require symfony/framework-bundle:${SYMFONY_VERSION}
   phpunit --configuration $DB.phpunit.xml
